### ISSUE TITLE
Single Brigade project, multiple GitHub repositories

### ISSUE THREAD

**Issue by esilkensen** [brigadecore/brigade-github-app#89]
We have a Brigade project that analyzes our GitHub repositories and generates a "scorecard" for each repository - this currently runs every couple of hours on a cron schedule, but we'd really like to leverage this app to run it as a GitHub check.

From the [docs](https://github.com/brigadecore/brigade-github-app#6-add-brigade-projects-for-each-github-project), it sounds like this would mean creating a separate Brigade project for each repository though, and we have 100+ repositories.

I'm wondering if it's a hard requirement that there be a project for each repository, or if it's possible the app could be extended somehow to work with a single Brigade project + many GitHub repositories? 
 (Maybe something analogous to the `defaultSharedSecret` value, like `defaultProject`?)

**Comment by radu-matei** [comment]
Does this really need to use the GitHub gateway app for _every_ repo though?

We use the GitHub gateway app because we want to execute `brigade.js` files based on events triggered by actions _in individual_ repositories (a new PR was opened - clone that particular branch, run tests..).
But it seems like in your case you could have a single Brigade project + repository where the cron job would clone all repositories and generate your scorecard - this project would basically aggregate everything.

The change you suggested is definitely worth investigating - this would, however, allow you to use the current versions without one project per repo.
Does it make sense?

**Comment by esilkensen** [comment]
Thanks @radu-matei - I think you actually described our current approach: we have a single Brigade project and a "scorecard generator" repository, and when it runs it generates a scorecard for each of the 100+ other repositories. Instead of cloning those repositories, it makes GitHub API calls to check their contents.

We'd like to be able to trigger it via actions in individual repositories and be able to show the result as a GitHub check in PR's, for example, instead of only running in batch as a cron job.

**Comment by krancour** [comment]
Events can include a cloneURL that overrides the project cloneURL. So, if you created a custom gateway that triggered the one brigade project, it could set the cloneURL to be that if whichever repo triggered the event. However, since this repo won't necessarily have a brigade.js file in it (since I imagine you want to manage that centrally) you would have to set a be default brigade.js at the project level.

**Comment by esilkensen** [comment]
Sounds good -- I'm not sure if I followed everything, but right, I think we do want a centrally located brigade.js file if possible.

Taking an initial glance at the code, I wondered about: https://github.com/brigadecore/brigade-github-app/blob/165234b5c305c128454bd897e71de611cf0e4b6a/pkg/webhook/github.go#L440-L448

Would it make sense for this `getValidatedProject` function to potentially have logic along the lines of:

* if the `Context` has some new parameter (`defaultProject`, `defaultRepo`, etc.), then use that as the parameter to `s.store.GetProject`, overriding the `repo` value from the event?

i.e. could we trigger a Brigade project based on GitHub webhook events, without regard to what GitHub repo the events are tied to? 

Or maybe how I'm thinking about this simply isn't the way the app is intended to be used?

**Comment by krancour** [comment]
> Would it make sense for...

I was having a little trouble following the suggestion, but backing up a step or two and just looking at the bigger picture as described a few comments back, I do understand what you're after. You want events (webhooks) originating externally from _n > 1_ GitHub repositories to trigger a build on _one_ Brigade project.

> Or maybe how I'm thinking about this simply isn't the way the app is intended to be used?

Nothing technically prevents _Brigade_ from handling this use case, _however_, the `brigade-github-app` (i.e. the _gateway_) was certainly not created with your use case in mind. It was designed to receive external events from GitHub repos and _emit_ them into Brigade, triggering a build on one project whose name precisely matches the repository from which the event originated. i.e. The gateway is quite opinionated in how it matches events to projects and it assumes a 1:1 relationship between GitHub repos and Brigade projects, _not_ n:1.

This gateway works well for this common 1:1 case, and enhancing it to handle the n:1 case, imho, would add an undesirable degree of new complexity. (And then someone will inevitably ask for 1:n, which would add more complexity still.)

Please make no mistake-- your use case is perfectly valid, but it's not what this gateway was designed for.

> I'm not sure if I followed everything

If you don't mind me revisiting my suggestion in greater detail...

At its heart, Brigade is about connecting _arbitrary event sources_ with arbitrary containerized logic. Most Brigade users only ever need to define the "arbitrary containerized logic" part of that equation by scripting a `brigade.js`, but the role of custom gateways in implementing those "arbitrary event sources" shouldn't be understated.

Your custom gateway could be relatively simple. It would receive webhook events (and at that, only the ones you care about; ignoring the rest) from whichever / however many GitHub repos you like, but would "fan in" to emit events into Brigade for just a _single_ project. (Which project? 🤷‍♂ You could make it deploy-time configurable or could probably even get away with hard coding it.) Apart from the "fan in" action, the only other thing the gateway would have to do is set the `cloneURL` field correctly on the events it emits into Brigade so that all builds of the single project know _which_ of the n repositories to clone when proceeding with the build.

Since you have n GitHub repositories and won't want to store a copy of your `brigade.js` in each and every one of those, you should store the `brigade.js` _directly_ in the one Brigade project's configuration. i.e. Use the `defaultScript` field of the project.

The lifecycle for any given event then is this:

1. Any of n GitHub repos sends a webook request to your new, custom gateway.
2. Gateway sets `cloneURL` appropriately on a new event that it emits into Brigade. It always triggers the _same_ Brigade project.
3. Brigade will honor the event's `cloneURL` field when it fires up a worker (pod) to handle the build. Your worker will get source from the _correct_ repo. (You don't have to do anything here in no.3. This is just how it works.)
4. The source from whichever repo was cloned will not contain a `brigade.js` file. The worker will therefore fall back on using the default `brigade.js` file defined by the project's `defaultScript` field. (Again... no need to do anything here. This is just how it works.)
5. `brigade.js` will execute and do whatever it's supposed to _on whichever repo originally set these events in motion._ If the worker fans out to create subordinate jobs, even those jobs will automatically use the correct repo. (Again... nothing to do here. It's just how it works.)

I hope this makes things a little more clear.

fwiw, a gateway that handles these n:1 situations could be useful to other folks, so you could even consider open-sourcing whatever solution you come up with.

**Comment by esilkensen** [comment]
Thanks so much, @krancour! Yes, that makes things much more clear, and I will certainly hope to open source that n:1 gateway if I am able to build it. I will go ahead and close this issue, thanks again all for the discussion.
