### ISSUE TITLE
Simplify instructions for CD pipeline

### ISSUE THREAD

**Issue by sbussard** [brigadecore/brigade-github-app#92]
Please add documentation for the smallest possible CD use case, to speed up the process of vetting this tool for newcomers 🙋‍♂️

Since 
> The installation for this gateway is multi-part, and not particularly easy at the moment.

Innocent-looking instructions like 
> Set the Webhook URL to https://YOUR_DOMAIN/events/github

Involve an unknown set of potentially unnecessary steps that cause quite a bit of fatigue, especially after installing yet another cli.

How can a newcomer navigate these waters without getting lost at sea? 
Is is absolutely necessary to create a github app?
Is there a way to interact with a cUrl command or github webhook?

Please consider making instructions for the smallest possible CD use-case. Thank you

**Comment by krancour** [comment]
> The installation for this gateway is multi-part, and not particularly easy at the moment.

This statement, unfortunately, remains true. It seems you've already figured this out, but allow me to emphasize for anyone else viewing this thread that the intricacies of setting this up are on the GitHub end and not really on the Brigade end.

That said, I understand the frustration.

> Is is absolutely necessary to create a github app?

Given that the Brigade GitHub gateway specifically integrates with GitHub Apps, I'm not aware of any shortcuts you could take on the GitHub end that would remain compatible with the gateway.

> Is there a way to interact with a cUrl command...

Of course you _can_ send requests to the Brigade GitHub gateway using curl, but crafting a mock request payload that would sufficiently emulate a real event from GitHub Apps would be non-trivial to an extent that you're better off just setting up a GitHub App. Even if you did incur the effort to mock up some requests, your mileage will vary because the gateway, in some cases, talks back to GitHub Apps through their API, so without having set all of that up, some things will fail.

> or github webhook?

Again, with the gateway integrating specifically with GitHub Apps, I don't believe non GitHub Apps webhooks to be compatible with the gateway, although anyone is welcome to put that to the test if they'd like.

> How can a newcomer navigate these waters without getting lost at sea?

Since the intricacies of setting up a GitHub App can indeed be quite onerous, I would not suggest this as the starting point for someone who's just kicking the tires. There's pretty good availability of documentation covering simpler use cases that should adequately illustrate the mechanics and capabilities of Brigade. Although a common use case, the unfortunate intricacies of setting up a GitHub App probably qualify it as an advanced one.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.

fwiw, we believe we've streamlined the setup instructions significantly for the Brigade v2-compatible GitHub gateway.
